---
exclude_paths:
  - '.github/**'
  - '.github/**/*'
  - 'docs/**'
  - 'www/inc/ssp.class.php'
  - 'www/js/bootstrap/**'
  - 'www/js/ckeditor/**'
  - 'www/js/datatables/**'
  - 'www/js/FontAwesome/**'
  - 'www/js/jquery/**'
  - 'www/js/mark.js/**'
  - 'www/js/noty/**'
  - 'www/js/setup/**'
  - 'www/js/select2/**'
  - 'README.md'
