---
exclude_paths:
  - '.github/**'
  - '.github/**/*'
  - 'doc/**'
  - 'js/bootstrap/**'
  - 'js/ckeditor/**'
  - 'js/cookie/**'
  - 'js/datatables/**'
  - 'js/FontAwesome/**'
  - 'js/jquery/**'
  - 'js/noty/**'
  - 'README.md'
