---
exclude_paths:
  - '.github/**'
  - '.github/**/*'
  - 'docs/**'
  - 'inc/ssp.class.php'
  - 'js/bootstrap/**'
  - 'js/ckeditor/**'
  - 'js/datatables/**'
  - 'js/FontAwesome/**'
  - 'js/jquery/**'
  - 'js/mark.js/**'
  - 'js/noty/**'
  - 'js/setup/**'
  - 'README.md'
