# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
dist: trusty

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.x
  #- 5.2 # only on precise
  #- 5.3 # only on precise
  - 5.4
  - 5.5
  - 5.6

  # aliased to a recent 7.x version
  - 7.0
  - 7.1
  - 7.2

  # aliased to a recent hhvm version
  #- hhvm # not supported on Ubuntu precise. Consider using trusty
  #- nightly

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# optionally set up exclusions and allowed failures in the matrix
#matrix:
#  exclude:
#    - php: hhvm
#      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
#  allow_failures:
#    - php: 7.0
#    - php: hhvm

#before_install:

install:
  - composer install --no-interaction

# execute any number of scripts before the test run, custom env's are available as variables
#before_script:
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - phpunit --bootstrap www/inc/helperFunctions.php tests/helperFunctionsTests.php
  #- npm run docs

after_success:
  - ./.travis_publish_docs

#after_script:

#before_deploy:

#after_deploy:


# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"
