# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
dist: trusty

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:1.* squizlabs/php_codesniffer:2.* -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require phpstan/phpstan:^0.10.3 -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n ; fi

# execute any number of scripts before the test run, custom env's are available as variables
#before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi


# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then vendor/bin/phpunit ; fi
  - phpunit --bootstrap inc/helperFunctions.php tests/helperFunctionsTests.php
